services:
  portfolio:
    build:
      context: .
      args:
        SITE_URL: ${SITE_URL:-}
    container_name: portfolio-jd
    restart: unless-stopped
    ports:
      - "4001:80"
    networks:
      - mon-reseau

networks:
  mon-reseau:
    external: true
